### ISSUE TITLE
API 초안 작성

### ISSUE THREAD

**Issue by AlbertImKr** [weaverse-techtide/weaverse-backend#5]

**Comment by devnproyj22** [comment]
## API 초안 (figma)
(Agenda: 백엔드 개발자로써 프론트엔드 개발자에게 전달할 내용)
- [ ] figma 사용 설명서
- [ ] Essential Endpoints List & Link
- [ ] Endpoint > Essential Django data fields
- [ ] Endpoint > Essential Structure of Response JSON
- [ ] Endpoint > Discussion Lists
- [ ] course -> lecture -> topic -> mission, video
